{% set name = "unbaffeld" %}
{% set version = "0.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/UNBAFFELD-{{ version }}.tar.gz
  sha256: bea846dd6a07ff65b5e021603293dff3348f17ad113c333fa5f695168251cc7c

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - inference-tools >=0.12.0
    - numpy >=1.8
    - scipy >=1.6.3
    - h5py
    - matplotlib >=3.4.2

test:
  imports:
    - unbaffeld
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: "https://gitlab.com/efit-ai/unbaffeld"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "UNBAFFELD: UNified Bayesian Analysis Framework for Fusion ExperimentaL Data"
  doc_url:
  dev_url: http://www.gitlab.com/efit-ai/unbaffeld

extra:
  recipe-maintainers:
    - JarrodLeddy
